### ISSUE TITLE
Get rid of redundant code in [Util/VKReader/TWReader].UIBroker

### ISSUE THREAD

**Issue by deadpadre** [intersystems-ru/iknowSocial#14]
Changes in branch `map-colorer` demand changes for `Twitter.UI`: it should be inherited from `Util.UIBroker` and renamed to `Twitter.UIBroker`. Feel free to connect with me in skype to discuss this refactoring.

**Comment by ssolomaha** [comment]
Refactor Twitter.UI to map-colorer branch.

**Comment by deadpadre** [comment]
I still don't like this code.
We have doubling methods such as `ShowFullSourceById` and 'AddMorePostsWithinContext'.
I want to make `Util.UIBroker` registered, introduce context property and make classmethods just instance methods. Let's dicuss it on wednesday meeting.

**Comment by deadpadre** [comment]
Last merge from `map-colorer` closes this issue.
